import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar/Navbar";
import Footer from "@/components/layouts/Footer/Footer";
import localFont from 'next/font/local'

const poppins = Poppins({
   weight: ["100",'200', "400", "500", "600", "800"],
 })


export const fontBangla = localFont({
   src:'./../fonts/mayaboti-normal.ttf'
 })
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`${poppins.className} antialiased`}
      >
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar/>
        </header>
        <main className="py-2 md:w-11/12 mx-auto ">

        {children}
        </main>
        <footer className="py-2 md:w-11/12 mx-auto">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
